---
- name: Fedora/Ubuntu Workstation
  hosts: localhost
  become: true

  pre_tasks:

    - name: Carregar variáveis da distribuição
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/{{ ansible_facts['distribution'] }}.yml" 

  roles:
    - repositories
    - common
    - git
    - git_config
    - docker
    - postgres
    - nginx
    - google_chrome
    - vscode
    - fonts
    - ssh
    - zsh
